#!/usr/bin/env python

import re
from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("readline"))

def E(s, trim=False):
    """Expand $En in s to the environment ID of the n'th user
    environment."""

    tmpl = "%x" if trim else "%08x"
    return re.sub(r"\$E([0-9]+)",
                  lambda m: tmpl % (0x1000 + int(m.group(1))-1), s)

@test(5)
def test_primes():
    r.user_test("primes", stop_on_line("CPU .: 1877"), stop_on_line(".*panic"),
                make_args=["CPUS=4"], timeout=30)
    r.match(E(".00000000. new env $E1"),
            E(".$E1. new env $E2"),
            E("CPU .: 2 .$E2. new env $E3"),
            E("CPU .: 3 .$E3. new env $E4"),
            E("CPU .: 5 .$E4. new env $E5"),
            E("CPU .: 7 .$E5. new env $E6"),
            E("CPU .: 11 .$E6. new env $E7"),
            E("CPU .: 1877 .$E289. new env $E290"))

end_part("C")

run_tests()
